# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982f5948e5b01444f2eac7bbdc94682460ba94ed47872b1d61d5d3495e4e37de287df5714ebbe503c88531bcc11ac4c7566298a6f964e3bd2aacdff12c977381

test:
  secret_key_base: c9a1e88c46bb975fccf45f17574af488cafdb4f63ca3c4f49dbd1ef9ae1bdb267e1049328a2dc2e03d248246ee3e95b562f85111aba261be7a0c62ab1ce8f7ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
